### ISSUE TITLE
pwa-starter-kit

### ISSUE THREAD

**Issue by Link2Twenty** [pwa-awards/website#3]
Is it worth building this site on https://github.com/Polymer/pwa-starter-kit so it's compliant with PWA standards itself?

**Comment by RobertJGabriel** [comment]
Hey. We can, the site itself is almost at the pwa standards just needs to be cleaned up. Any other reasons you recommend this ?

**Comment by Link2Twenty** [comment]
I quite like web components and this kit is built on polymer which makes web components easy.
